version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/gardenit
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: changeme
      PERENUAL_API_KEY: ${PERENUAL_API_KEY:-}
      OPEN_METEO_BASE_URL: ${OPEN_METEO_BASE_URL:-https://api.open-meteo.com/v1/forecast}
      EMAIL_SERVER: ${EMAIL_SERVER:-smtp://user:pass@smtp.local:1025}
      EMAIL_FROM: ${EMAIL_FROM:-gardenit@example.com}
    command: pnpm start

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: gardenit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gardenit"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
